# Generated by Django 5.0.6 on 2024-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "dependent_templates",
                    models.ManyToManyField(
                        blank=True, related_name="parent_templates", to="app.template"
                    ),
                ),
            ],
        ),
    ]
